###########################################
## @Author: 陈小鹏
## @Date: 2022-12-26 16:27:56
## @LastEditors: Please set LastEditors
## @LastEditTime: 2022-12-26 17:15:52
## @FilePath: /peng/启动/Makefile
###########################################

目录 = mbr	\

include $(SRoot)/peng/PengOS.mk